# Generated by Django 5.1.6 on 2025-02-14 08:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, help_text='Tell others about yourself.', null=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('non-binary', 'Non-Binary'), ('other', 'Other'), ('prefer_not_say', 'Prefer not to say')], default='prefer_not_say', max_length=20)),
                ('age', models.PositiveIntegerField(blank=True, help_text='Enter your age.', null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('interests', models.TextField(blank=True, help_text='List your hobbies and interests.', null=True)),
                ('relationship_goal', models.CharField(choices=[('casual', 'Casual Dating'), ('serious', 'Serious Relationship'), ('friendship', 'Friendship'), ('unsure', 'Not Sure Yet')], default='unsure', max_length=20)),
                ('profile_image', models.ImageField(default='profile_pics/default.jpg', upload_to='profile_pics/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
