# Generated by Django 5.1.6 on 2025-02-16 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0001_initial'),
    ]

    operations = [
    ]
from django.db import migrations

def create_initial_questions(apps, schema_editor):
    Question = apps.get_model('questionnaire', 'Question')
    Choice = apps.get_model('questionnaire', 'Choice')

    # Spark Type Question
    spark_q = Question.objects.create(
        question_text="What kind of spark are you looking for?",
        question_type='SINGLE',
        category_id=1,
        order=1
    )
    spark_choices = [
        "Long-term Relationship",
        "Casual Dating",
        "Marriage",
        "Friendship"
    ]
    for text in spark_choices:
        Choice.objects.create(question=spark_q, text=text)

    # Gender Preference Question
    gender_q = Question.objects.create(
        question_text="What gender(s) are you interested in?",
        question_type='MULTIPLE',
        category_id=1,
        order=2
    )
    gender_choices = [
        "Men",
        "Women",
        "Non-binary",
        "Other"
    ]
    for text in gender_choices:
        Choice.objects.create(question=gender_q, text=text)

    # Age Preference Question
    age_q = Question.objects.create(
        question_text="What age range(s) are you interested in?",
        question_type='MULTIPLE',
        category_id=1,
        order=3
    )
    age_choices = [
        "18-24",
        "25-34",
        "35-44",
        "45-54",
        "55+"
    ]
    for text in age_choices:
        Choice.objects.create(question=age_q, text=text)

def remove_initial_questions(apps, schema_editor):
    Question = apps.get_model('questionnaire', 'Question')
    Question.objects.all().delete()

class Migration(migrations.Migration):
    dependencies = [
        ('questionnaire', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_initial_questions, remove_initial_questions),
    ]
