# Generated by Django 5.1.6 on 2025-02-15 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0002_userresponse'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questioncategory',
            options={'verbose_name_plural': 'Question Categories'},
        ),
    ]
